name: Make prebuilt binaries

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, i686-pc-windows-gnu, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-unknown-linux-gnu, i686-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust version
        run: rustc --version

      - name: Build library
        run: cargo build --release --target {{ matrix.target }}

      - name: Create tar.gz
        run: tar -czf  libtuile_crossterm-${{ matrix.target }}.tar.gz target/${{ matrix.target }}/release/libtuile_crossterm.a tuile-crossterm.h

      - name: Attach to release
        uses: softprops/action-gh-release@v1
        with:
          files: libtuile_crossterm-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
